apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: techdome-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techdome-database
  template:
    metadata:
      labels:
        app: techdome-database
    spec:
      containers:
        - name: database
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: techdome
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-storage
          emptyDir: {} # For testing purposes; replace with persistent volume in production
