apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: techdome-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techdome-frontend
  template:
    metadata:
      labels:
        app: techdome-frontend
    spec:
      containers:
        - name: frontend
          image: your-frontend-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://backend:5000 # Backend service address
