apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: techdome-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort # Exposes the frontend to be accessed externally via Minikube
